### PR TITLE
Introduce "warning" policy; change no-var to a warning

### PR DESCRIPTION
**Pull request by feross**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix
[x] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

Explain the difference between errors and warnings in the FAQ. Prep for releasing 16.0.1.

**Which issue (if any) does this pull request address?**

https://github.com/standard/standard/issues/633

**Is there anything you'd like reviewers to focus on?**

- Is the explanation about the difference between errors and warnings clear enough?
- Does the policy make sense?

### CODE REVIEW

**Comment by feross** [comment]
@standard/team - can you take a look at this?

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mafintosh** [comment]
I think warnings are a great way to check if a change has impact on newly written modules or existing ones with a high velocity of changes without having to worry about breakage to existing “finished” ones so big 👍 from me

**Comment by feross** [comment]
Thanks for the reviews, @mcollina and @mafintosh!

**Comment by feross** [comment]
Released as 16.0.1

**Comment by LinusU** [comment]
Awesome work getting this out quickly! 🌟

**Comment by feross** [comment]
Thanks @LinusU ❤️

**Pull request merged**
