### PR TITLE
Upgrade to ESLint 7

### PR DESCRIPTION
**Pull request by LinusU**
ref: #1518

Blocked on:

- [x] https://github.com/yannickcr/eslint-plugin-react/pull/2635
- [ ] https://github.com/standard/eslint-config-standard/pull/169
- [ ] https://github.com/standard/eslint-config-standard/pull/170

Tests blocked on:

- [x] https://github.com/webtorrent/webtorrent/pull/1856
- [x] https://github.com/webtorrent/parse-torrent/pull/85

Todo:
- [ ] https://github.com/standard/eslint-config-standard/issues/171
- [ ] Upgrade to eslint-config-standard 15.0.0
- [ ] Upgrade to eslint-plugin-react 7.20.0

### CODE REVIEW

**Comment by Raynos** [comment]
I reviewed all related PRs.

3 have merged and two have been approved.

**Comment by sheerun** [comment]
oh man, can't wait :)

**Comment by Raynos** [comment]
I’m not comfortable merging these PRs as is. 

Would it be ok to create a temporary git repo standard7 and eslint-config-standard7 ?

I can merge all these PRs in there and then publish new npm packages standard7 / eslint-config-standard7 .

The community can play with these packages and once all the bugs are worked out everything can be merged into standard version 15

Cc @linusu @feross @voxpelli

**Comment by voxpelli** [comment]
I would suggest we merge them all to a 15.x branch and publish a 15.x prerelease from that branch instead

**Comment by feross** [comment]
I'm working on this today.

**Review by feross — APPROVED** [review]
LGTM

**Pull request merged**
