### PR TITLE
Create Dependabot configuration

### LINKED ISSUE #1550: Greenkeeper bot is dead, migrate to another bot
**What version of this package are you using?**

Not relevant.

**What operating system, Node.js, and npm version?**

Not relevant.

**What happened?**

Your Greenkeeper dependency checker bot is dead.

Quote from the [Greenkeeper.io website](https://greenkeeper.io/):
> We’ll stop Greenkeeper’s operation as an independent service on June 3rd, 2020.
> For your dependency update needs, we have a brilliant alternative for you: **Snyk**.

This means there are no automated dependency checks anymore.

**What did you expect to happen?**

A bot that checks for updates to dependencies is running on this repository.

**Are you willing to submit a pull request to fix this bug?**

Yes, I can get you a Dependabot configuration tuned to your liking if you want.
I can also get you pointed in the right direction for Renovate.

**Migrate to Dependabot**

This is probably the easiest migration I can offer you, because I can do the configuration work for **Dependabot** together with you. If you want I can open a pull request that gets you a basic Dependabot configuration, which I will then tune to your liking according to your feedback.

The main benefit of Dependabot is that it's easy to use and integrated into GitHub. You won't need to use another app/website to manage the bot.

The downside is that you can't really configure Dependabot to only offer certain patch level updates (major only, major and minor, major + minor + patch). Dependabot also doesn't know how to group updates together that should be upgraded as a group.

[Dependabot Documentation](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/keeping-your-dependencies-updated-automatically)

**Migrate to Depfu**

Or you can take a look at **Depfu**, which supports setting the level of updates you want, and will group updates that belong together into one pull request by default.

[Depfu app on GitHub Marketplace](https://github.com/marketplace/depfu)

**Migrate to Renovate**

Or maybe you like **Renovate** better, it also supports setting the level of updates you want, and supports grouping updates that belong together into one pull request (most known monorepos are grouped by default).

Renovate is quite easy to get started with, they have a "getting started" pull request, that helps you to configure the bot to your liking.

[Renovate app on GitHub Marketplace](https://github.com/marketplace/renovate)

**Migrate to Snyk**

Or you can do what Greenkeeper suggests and use Snyk.
[Snyk app on GitHub marketplace](https://github.com/marketplace/snyk)

**Checklist for migration**

- [x] Decide which bot you want to use.
- [x] If you want to use Dependabot, ping me, and I'll make a basic config, and ask you what you want/don't want.
- [ ] Ensure new bot works.
- [ ] Remove Greenkeeper app from this repository.
- [x] Close old Greenkeeper pull requests.

### PR DESCRIPTION
**Pull request by HonkingGoose**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix
[ ] New feature
[x] Other, please explain: Configure Dependabot so that you have a working dependency bot.

**What changes did you make? (Give an overview)**

- Create a Dependabot config.

**Which issue (if any) does this pull request address?**

Closes #1550

**Is there anything you'd like reviewers to focus on?**

**References:**

[Official GitHub Dependabot configuration options documentation](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates)

**Things you probably should do after merging:**

- [ ] Delete Greenkeeper app, see the [GitHub Docs on deleting a GitHub app](https://docs.github.com/en/free-pro-team@latest/developers/apps/deleting-a-github-app).
- [ ] Remove stale Greenkeeper branches on this repository, see this [list of stale branches for standard/standard repository](https://github.com/standard/standard/branches/stale).

### CODE REVIEW

**Comment by feross** [comment]
- Daily is fine
- No specific time
- Don't assign to anyone
- Don't request a review
- No particular commit format
- You can apply the label `dependency`
- The "increase" strategy looks good

And my question for you?

- Is there a way to apply this configuration to the whole `standard` GitHub organization?

**Comment by HonkingGoose** [comment]
### Is there a way to apply this configuration to the whole `standard` GitHub organization?

There is no setting in Dependabot, that I know of, to source a config file from a separate repository like `dependabot-config-repository`. I think you can use *Git Submodules* to cobble something together, but this would only work if the wanted config is **exactly the same** across repositories.

See [ProGit2 book, chapter 7.11 Git Tools - Submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) to see how that would work. I don't think this is easier to use than just using a separate config for each repository though. I think a Git submodule adds more complexity for little benefit.

If this is something that you really want, I can help you with a Renovate config instead. With Renovate you can create a base config in a separate repo that other repositories then extend from.

**Comment by HonkingGoose** [comment]
@feross I answered your question, take a look at the post above this one. :wink:

**Review by feross — APPROVED** [review]
LGTM. Let's try this out. If it works well, then we can add this file to all the `standard` repos.

**Comment by HonkingGoose** [comment]
@feross You might want to remove the stale branches that are left over from the old Greenkeeper bot: https://github.com/standard/standard/branches/stale

**Comment by feross** [comment]
@HonkingGoose Thanks for the suggestion – fixed!

**Comment by HonkingGoose** [comment]
Cheers! :smile:

**Pull request merged**
