### PR TITLE
Update the list of default ignored files in documentation

### PR DESCRIPTION
**Pull request by ciffelia**
**What is the purpose of this pull request? (put an "X" next to item)**

[X] Documentation update
[ ] Bug fix
[ ] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
Remove `bundle.js` from the list of of default ignored files, because it is no longer ignored. (https://github.com/standard/standard-engine/commit/1319c5b4d6b39eecf909a7072ae92eabe36e0213)

**Which issue (if any) does this pull request address?**
#743

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by ciffelia** [comment]
@mightyiam This is the commit that removed `bundle.js`. https://github.com/standard/standard-engine/commit/1319c5b4d6b39eecf909a7072ae92eabe36e0213

**Comment by mightyiam** [comment]
I don't understand how a single person can reasonably edit documentation in multiple languages. You don't know all of these languages — right, @ciffelia? Could the edit to one of these translations be erroneous?

How do we handle this? What's the strategy here?

**Comment by ciffelia** [comment]
@mightyiam You're right. I thought removing a word from docs can be done without knowledge of languages, but actually I'm not sure. If you think this change should be reviewed by translation contributors, I will revert changes on translated docs.

**Comment by mightyiam** [comment]
From my perspective, without a readily-available team of translators, this is unmaintainable. I suggest that authors modify only languages that they know and then if language contributors care, they will follow pull requests and contribute updates to documentation.

**Comment by LinusU** [comment]
I personally think that it's probably fine, seems like a reasonable change in all languages 👍

**Comment by mightyiam** [comment]
Yes, I took a close look and it seems fine.

**Comment by mightyiam** [comment]
But languages have quirks that you wouldn't imagine.

**Comment by ciffelia** [comment]
As @mightyiam pointed out, I can't guarantee the correctness of translations, so I'll revert changes on them for now.

**Comment by ciffelia** [comment]
And as a Japanese speaker, I'm sure that the Japanese translation is correct.

**Pull request merged**
