### PR TITLE
remove ads

### PR DESCRIPTION
**Pull request by WheresAlice**
This should be pretty self-explanatory - removes the unwanted NPM package which is injecting ads into standard.

### CODE REVIEW

**Comment by TooMuchFun** [comment]
Wow. Get rid of that trashy bot. What a joke you've become... webtorrent was pretty cool when it lasted.

**Comment by WheresAlice** [comment]
This seems to be the popular opinion in #1381

**Comment by miguelmota** [comment]
Very nice PR 👍

**Comment by LinusU** [comment]
Please keep the discussion to #1381, when **@feross** takes a decision based on the feedback there he can make this change directly. Thanks!

**Pull request closed without merging**
