### PR TITLE
🇯🇵 Add Japanese translation for document

### LINKED ISSUE #1202: Can I add Japanese translation for document?
Hi, I'm Japanese engineer (and native Japanese speaker)🇯🇵
I'd like to translate documents to Japanese.
Can I do that?

like this:

### PR DESCRIPTION
**Pull request by munierujp**
fix #1202

### CODE REVIEW

**Comment by munierujp** [comment]
I'll fix sume Markdown syntax (e.g. `**bold**`).
This PR is work in progress now.

**Comment by munierujp** [comment]
I've fixed Markdown syntax.

**Comment by munierujp** [comment]
Please review this 🙇

**Comment by constdrop** [comment]
I am Japanese engineer too. Can I join this PR? Or after marged this, then I create new PR.
I have another translation in Japanese for myself. And it might be contribute this project.

**Comment by brodybits** [comment]
??

**Comment by LinusU** [comment]
ping @Flet, @feross, do we just merge PRs like this? Since I'm guessing none of us knows Japanese? 🤔

**Comment by munierujp** [comment]
I'm now finding Japanese reviewer...

https://twitter.com/munieru_jp/status/1097637174957068288

**Comment by kohashi** [comment]
@munierujp Hi! And It's seems great translation!
But there seems to be some verbose/redundant points.
And I append/fix those points and make Pull Request. (Many fixes but small fixes.)

https://github.com/munierujp/standard/pull/10

**Comment by munierujp** [comment]
Some redundant Japanese has fixed by @kohashi

**Comment by brodybits** [comment]
🔔🔔

**Comment by feross** [comment]
This is amazing work!! Thank you for this effort and sorry for the delay in reviewing this PR!

**Comment by feross** [comment]
@kohashi Feel free to send your improvements in a further PR!

**Pull request merged**
