### PR TITLE
Use hallmark to lint and fix markdown

### LINKED ISSUE #1606: Use `hallmark` to lint/generate the changelog
Based on discussion with @vweevers, we can use `hallmark` to lint/generate the changelog.

_Originally posted by @feross in https://github.com/standard/standard/issues/1600#issuecomment-728689497_

### PR DESCRIPTION
**Pull request by vweevers**
**What is the purpose of this pull request?**

- [x] Documentation update

**What changes did you make?**

I separated this PR into multiple commits for review purposes. It can be merged as one.

The first commits are manual changes to `CHANGELOG.md`: ee72ed6, f7f9154, 50cf0fc, f2f87fb. These commits make it so you can run `hallmark lint CHANGELOG.md` without lint errors. Which also means you can run `hallmark bump minor` (similar to `npm version minor`) to add a new changelog entry prepopulated with git commits.

The later commits (d9ceefc, 88af2e9, 2023291, b453273, 5af9072) are optional because they touch other markdown files and may affect the website. Specifically, they change the depth of headings and collapse the Table of Contents. On the plus side, the ToC is automatically updated when you run `hallmark fix`. If you like these commits then I can make the same changes to the translations in `docs/*.md`. Let me know. Depending on that, I will also add `hallmark` to the npm test script, either linting all files or only `CHANGELOG.md` to start.

**Which issue (if any) does this pull request address?**

Closes #1606.

**Is there anything you'd like reviewers to focus on?**

Is the changelog structure satisfying or should we consider alternative solutions?

### CODE REVIEW

**Review by Divlo — COMMENTED** [review]
I think, we could instead use [markdownlint](https://github.com/igorshubovych/markdownlint-cli) for linting markdown files.

**Review by duongxuantuan15 — COMMENTED** [review]
@vweevers 
#cam kết và hợp nhất

- [ ]

**Review by duongxuantuan15 — APPROVED** [review]
@duongxuantuan15

**Comment by vweevers** [comment]
Closing because hallmark is moving to [Common Changelog](https://common-changelog.org/). Which would require bigger changes to standard's changelog - mainly because Common Changelog does not allow arbitrary content like on [16.0.0](https://github.com/standard/standard/blob/master/CHANGELOG.md#1600---2020-10-28) and [16.0.1](https://github.com/standard/standard/blob/master/CHANGELOG.md#1601---2020-10-30).

Feel free to cherry-pick some of the commits here to improve markdown (CommonMark / remark) compatibility.

**Pull request closed without merging**
