### PR TITLE
Add readme & rules in korean

### PR DESCRIPTION
**Pull request by devjin0617**
Translate readme and rules in korean language and modify korean md link in all md files of readme and rules 😄

### CODE REVIEW

**Comment by devjin0617** [comment]
@feross Please confirm 😢

**Comment by feross** [comment]
@devjin0617 Sorry for the delay in reviewing this! Looks great to me!

I merged this and added you to the @standard organization so you can make further changes and PRs as the readme/docs evolve (if you want).

**Comment by devjin0617** [comment]
@feross wow! thank you 😄  I will continue to PR

**Comment by bcomnes** [comment]
Great work.  Translating is a thankless and laborious task.

**Pull request merged**
