### PR TITLE
Add Flowsent to companies using Standard

### LINKED ISSUE #1259: Getting standard; Pls add flowsent.com to the site
After speaking with @feross on Twitter, he said to open an issue saying we're using standard and to send our URL and logo to be added to the https://standardjs.com site under 'Who's Using StandardJS'. Thank you for making StandardJS and keeping code clean!

Our site adding it is **https://flowsent.com**. Logo attached.
F-Bird Cursive Purple Kush

Kind Regards,
Rick Bakas

### PR DESCRIPTION
**Pull request by LinusU**
Fixes #1259

### CODE REVIEW

**Comment by Flowsent** [comment]
Thank you for the updates.

**Comment by Flowsent** [comment]
@LinusU what would you like us to provide here to close this request? Shall we provide a screenshot of the code using Standard?

**Comment by LinusU** [comment]
Just need someone else to review the PR, nothing else is needed from you ☺️ 

ping @Flet, would you mind? ❤️

**Comment by LinusU** [comment]
Thanks 👏

**Pull request merged**
