### PR TITLE
Increase `daysUntilClose` for stale bot

### PR DESCRIPTION
**Pull request by voxpelli**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix
[ ] New feature
[x] Other, please explain:

Make stale bot a bit less aggressive for now

**What changes did you make? (Give an overview)**

Changed from 14 days between comment and close to 60 days

**Which issue (if any) does this pull request address?**

Gives us all more time to act on things

**Is there anything you'd like reviewers to focus on?**

Just whether we want this change or not

### CODE REVIEW

**Review by Divlo — COMMENTED** [review]
Is an inactive issue no longer an issue?
It might be better to basically disable it completely and that we don't use a stale bot and let us (maintainers) manage issues.

I might be missing something, but is a stale bot really useful? What problem does it solve?
Are humans not capable to close issues when they are no longer relevant?
There are many repos on GitHub that use a stale bot but why, what does it bring?

I didn't have a opinion for this PR: https://github.com/standard/standard/pull/1734 but now I'm wondering if it's really useful.
Feel free to explain a little bit more why for this bot.
Thanks.

**Comment by voxpelli** [comment]
I agree with you, I never use stale bots myself, I think an issue can be valid even if it's stale.

**Comment by LinusU** [comment]
I personally feel very discouraged when my issues are closed by stale bots. I'm +1 on removing it

**Comment by voxpelli** [comment]
@LinusU Seems like its a Probot app rather than a GH workflow, so I can't remove it as I'm not an admin, and we can't remove it through a PR.

Can you remove it and then close this?

Also: Maybe we could remove all Probot apps and instead use GH Actions?

**Comment by LinusU** [comment]
Removing it seems to remove it from all 26 repositories within the Standard organization 😅 

But I guess that that is what we want, right?

**Comment by voxpelli** [comment]
> Removing it seems to remove it from all 26 repositories within the Standard organization 😅
> 
> But I guess that that is what we want, right?

Yeah, I would say so

> > Also: Maybe we could remove all Probot apps and instead use GH Actions?
> 
> I think this sounds like a good idea 👍

There is already some precedent in that with the lock script: https://github.com/standard/standard/blob/master/.github/workflows/lock.yml

**Pull request closed without merging**
